spring:
  datasource:
    url: jdbc:h2:mem:employee_db
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
