server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: login-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
